version: '3'

services:
  app:
    build: ./api
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    stdin_open: true
    tty: true
    restart: always
    image: postgres:11.6
    ports:
      -  '5433:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      TZ: Asia/Tokyo
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: npm run dev
    depends_on:
      - app

volumes:
  pgsql-data:
  bundle: