default: &default
  adapter: postgresql
  encoding: unicode
  username: pguser
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: pgpass
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>