inherit_from: .rubocop_todo.yml

# @see default https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
AllCops:
  # ルール名の表示
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'docker/**/*'
    - 'db/**/*'
    - 'Dockerfile'
    - 'node_modules/**/*'
    - 'Procfile'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vagrant/**/*'
    - 'Vagrantfile'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  CacheRootDirectory: tmp

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
# Ruby3.0から文字列リテラルがデフォルトでfreezeになる予定。
# 移行シミュレーション用なのでオフ。
Style/FrozenStringLiteralComment:
  Enabled: false
# Railsではドキュメント用コメントはなるべく付けない方向なのでオフ。
Style/Documentation:
  Enabled: false
